version: "3.8"

services:

  backend:
    build: ./backend
    container_name: backend_api
    environment:
      DB_HOST: database
      POSTGRES_DB: studentdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "3000:3000"
    depends_on:
      - database
    restart: always

  database:
    build: ./database
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: